import Head from 'next/head'
import Landing from './Page'

export default function Home() {
  return (
    <>
      <Head>
        <title>Shopping Cart Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing/>
    </>
  )
}
